name = "m3u8proxy"
main = "cf_worker.js"
compatibility_date = "2024-03-04"

[vars]
DEFAULT_REFERER = "https://megacloud.blog"
DEFAULT_ORIGIN = "https://hianime.to"
ALLOWED_ORIGINS = "https://justanime.to,https://www.justanime.to,http://localhost:5173"
